### ISSUE TITLE
KeyError: 'objectSid'

### ISSUE THREAD

**Issue by thor-vath** [fox-it/BloodHound.py#1]
## Issue
bloodhound.py exits with "KeyError: 'objectSid'

## Steps to reproduce
- Executed setup.py install
- Executed bloodhound.py with flags: -u, -p, -d, -v

## Output
```
DEBUG: Authentication: username/password
DEBUG: Using DNS to retrieve domain information
DEBUG: Querying domain controller information from DNS
DEBUG: Using domain hint: <redacted>
INFO: Found AD domain: <redacted>
DEBUG: Found primary DC: <redacted>
DEBUG: Using LDAP server: <redacted>
DEBUG: Using base DN: DC=<redacted>,DC=<redacted>
INFO: Connecting to LDAP server: <redacted>
DEBUG: Connecting to <redacted>, port 389, SSL False
DEBUG: Authenticating to LDAP server
DEBUG: Found 1 domains
DEBUG: Found 10489 computers
DEBUG: Found 6733 groups
Traceback (most recent call last):
  File "./bloodhound.py", line 5, in <module>
    bloodhound.main()
  File "/tools/BloodHound.py-master/bloodhound/__init__.py", line 176, in main
    bloodhound.run(skip_groups=args.skip_groups, skip_computers=args.skip_computers)
  File "/tools/BloodHound.py-master/bloodhound/__init__.py", line 62, in run
    self.dc.fetch_all()
  File "/tools/BloodHound.py-master/bloodhound/ad.py", line 979, in fetch_all
    self.get_groups()
  File "/tools/BloodHound.py-master/bloodhound/ad.py", line 840, in get_groups
    gid = int(ADUtils.formatSid(entry['objectSid']).split('-')[-1])
KeyError: 'objectSid'
```

**Comment by dirkjanm** [comment]
I'd be very curious to see how you end up with a group without a SID, assuming that this occurs somewhere in the middle and not directly when you start the tool (otherwise it could indicate a different issue)?
Some better error handling on this part wouldn't hurt for sure unless I can reproduce this locally somehow and find out what is causing it.

**Comment by dirkjanm** [comment]
Can you try again with the updated version?

**Comment by dirkjanm** [comment]
Assuming this is fixed.
