### ISSUE TITLE
Issue Running the script in Kali

### ISSUE THREAD

**Issue by tbalz2319** [fox-it/BloodHound.py#10]
Hello,

When I try to run the script i get the following issue below:

bloodhound-python 

Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 11, in <module>
    load_entry_point('bloodhound==0.4.0', 'console_scripts', 'bloodhound-python')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/bloodhound/__init__.py", line 26, in <module>
    from impacket.ldap import ldapasn1
  File "/usr/local/lib/python3.6/dist-packages/impacket/ldap/ldapasn1.py", line 578
    def __init__(self, criticality=None, flags=0x00000007L, **kwargs):
                                                         ^
SyntaxError: invalid syntax

**Comment by dirkjanm** [comment]
Closing this one, feel free to reopen if above instructions don't fix the problem.

**Comment by Chainsaw-Sam** [comment]
Heey i have a probleme, i can't found bloodhound-python command
even i isntall with pip install bloodhound
i need help please
