### ISSUE TITLE
Default running issue: UnboundLocalError: local variable 'ad_domain' referenced before assignment

### ISSUE THREAD

**Issue by fbarre96** [fox-it/BloodHound.py#119]
Steps to reproduce in a fresh python docker:
```# docker run -ti python /bin/bash
root@7f900b8a0d08:/# cd
root@7f900b8a0d08:~# pip install bloodhound
...
root@7f900b8a0d08:~# bloodhound-python -c All -u svc_apache -p '*******' -d flight.htb
WARNING: Could not find a global catalog server, assuming the primary DC has this role
If this gives errors, either specify a hostname with -gc or disable gc resolution with --disable-autogc
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/bloodhound/__init__.py", line 303, in main
    ad.dns_resolve(domain=args.domain, options=args)
  File "/usr/local/lib/python3.10/site-packages/bloodhound/ad/domain.py", line 695, in dns_resolve
    if self.auth.userdomain.lower() != ad_domain.lower():
UnboundLocalError: local variable 'ad_domain' referenced before assignment
```
I fixed temporarily the issue on my side with an empty string declaration but I don't know if it's a good fix for all purposes.

**Comment by davehardy20** [comment]
I have the same issue.
New Kali install from 2022.4 build

$ bloodhound-python -d north.sevenkingdoms.local -u brand.stark -p iseedeadpeople -gc winterfell.north.sevenkingdoms.local -dc winterfell.north.sevenkingdoms.local -c all
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 33, in <module>
    sys.exit(load_entry_point('bloodhound==1.6.0', 'console_scripts', 'bloodhound-python')())
  File "/usr/local/lib/python3.10/dist-packages/bloodhound-1.6.0-py3.10.egg/bloodhound/__init__.py", line 303, in main
  File "/usr/local/lib/python3.10/dist-packages/bloodhound-1.6.0-py3.10.egg/bloodhound/ad/domain.py", line 695, in dns_resolve
UnboundLocalError: local variable 'ad_domain' referenced before assignment

Not sure how to fix this?

**Comment by dirkjanm** [comment]
thanks for the report, this should be fixed in the latest version from git. could you recheck?
