### ISSUE TITLE
ImportError: No module named ldap

### ISSUE THREAD

**Issue by Clemenzah** [fox-it/BloodHound.py#12]
Hello,

Tried installing it both ways (repo and with pip) but keep getting this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 11, in <module>
    load_entry_point('bloodhound==0.5.0', 'console_scripts', 'bloodhound-python')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/bloodhound/__init__.py", line 26, in <module>
ImportError: No module named ldap
```

I'm sure I've install all required modules but no success thus far.

**Comment by dirkjanm** [comment]
This sounds like you have an outdated version of impacket. Please make sure you remove the previous version and install the latest impacket version from their git: https://github.com/CoreSecurity/impacket

**Comment by Clemenzah** [comment]
Oh so stupid.. I assumed I was on the latest version. Upgrading to the latest release fixed it. Thanks for the quick reply.

**Comment by dirkjanm** [comment]
No problem, I will make the versions more specific in the setup.py so we can hopefully avoid this in the future, as the error message it gave you wasn't very helpful.
