### ISSUE TITLE
SSL Error: "Ssl wrapping error: EOF occurred"

### ISSUE THREAD

**Issue by kostrin** [fox-it/BloodHound.py#128]
I am bloodhound python from a Mac M1 against a domain with signing enabled. I keep getting this error:

    bloodhound-python -c All -u 'USERNAME' -p 'PASS' -d mydomain.com -dc dc.mydomain.com
    INFO: Found AD domain: mydomain.com
    INFO: Getting TGT for user
    INFO: Connecting to LDAP server: dc.mydomain.com
    INFO: Kerberos auth to LDAP failed, trying NTLM
    WARNING: LDAP Authentication is refused because LDAP signing is enabled. Trying to connect over LDAPS instead...
    INFO: Kerberos auth to LDAP failed, trying NTLM
    Traceback (most recent call last):
      File "/opt/homebrew/bin/bloodhound-python", line 8, in <module>
        sys.exit(main())
      File "/opt/homebrew/lib/python3.10/site-packages/bloodhound/__init__.py", line 338, in main
        bloodhound.run(collect=collect,
      File "/opt/homebrew/lib/python3.10/site-packages/bloodhound/__init__.py", line 79, in run
        self.pdc.prefetch_info('objectprops' in collect, 'acl' in collect, cache_computers=do_computer_enum)
      File "/opt/homebrew/lib/python3.10/site-packages/bloodhound/ad/domain.py", line 523, in prefetch_info
        self.get_objecttype()
      File "/opt/homebrew/lib/python3.10/site-packages/bloodhound/ad/domain.py", line 240, in get_objecttype
        self.ldap_connect()
      File "/opt/homebrew/lib/python3.10/site-packages/bloodhound/ad/domain.py", line 69, in ldap_connect
        ldap = self.ad.auth.getLDAPConnection(hostname=self.hostname, ip=ip,
      File "/opt/homebrew/lib/python3.10/site-packages/bloodhound/ad/authentication.py", line 117, in getLDAPConnection
        return self.getLDAPConnection(hostname, ip, baseDN, 'ldaps')
      File "/opt/homebrew/lib/python3.10/site-packages/bloodhound/ad/authentication.py", line 109, in getLDAPConnection
        bound = conn.bind()
      File "/opt/homebrew/lib/python3.10/site-packages/ldap3/core/connection.py", line 589, in bind
        self.open(read_server_info=False)
      File "/opt/homebrew/lib/python3.10/site-packages/ldap3/strategy/sync.py", line 57, in open
        BaseStrategy.open(self, reset_usage, read_server_info)
      File "/opt/homebrew/lib/python3.10/site-packages/ldap3/strategy/base.py", line 146, in open
        raise exception_history[0][0]
    ldap3.core.exceptions.LDAPSocketOpenError: ("('socket ssl wrapping error: EOF occurred in violation of protocol (_ssl.c:997)',)",)
The following are my versions:

    python --version  
    Python 3.11.2

    python -c "import ssl;print(ssl.OPENSSL_VERSION)"
    OpenSSL 1.1.1t  7 Feb 2023

    Name: ldap3
    Version: 2.9.1

    Name: dnspython
    Version: 2.3.0

All of my Google foo says it is a M1 error with Outdated OpenSSL. But I tried updating the software but also a clean install in docker and even Kali. Unfortunately, I am getting the same result for all platforms. This is a legacy domain I am dealing with. Anyone have any idea what this could be?

**Comment by dirkjanm** [comment]
Are you sure the host has SSL configured and a certificate? When this is not set up properly the LDAPS port will be open but it will refuse connections. You can try connecting with other LDAP tools (such as ldp.exe for example) over LDAPS or try connecting with openssl directly on port 636 to see if there are any error messages.

**Comment by kostrin** [comment]
Thanks! This was exactly the issue was. The service was accepting connections, but using a none cipher and delivering no certs. Thanks for the help!
