### ISSUE TITLE
Running BloodHound.py

### ISSUE THREAD

**Issue by mrchelli** [fox-it/BloodHound.py#13]
I get this error message when trying to run BloodHound.py on my virtual network:

C:\Users\alice\Downloads\BloodHound.py-master\BloodHound.py-master>bloodhound-python
Traceback (most recent call last):
  File "c:\users\alice\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\alice\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\alice\AppData\Local\Programs\Python\Python37\Scripts\bloodhound-python.exe\__main__.py", line 5, in <module>
  File "c:\users\alice\appdata\local\programs\python\python37\lib\site-packages\bloodhound\__init__.py", line 26, in <module>
    from bloodhound.ad.domain import AD, ADDC
  File "c:\users\alice\appdata\local\programs\python\python37\lib\site-packages\bloodhound\ad\domain.py", line 33, in <module>
    from bloodhound.ad.computer import ADComputer
  File "c:\users\alice\appdata\local\programs\python\python37\lib\site-packages\bloodhound\ad\computer.py", line 27, in <module>
    from impacket.dcerpc.v5 import transport, samr, srvs, lsat, lsad, nrpc, wkst
  File "c:\users\alice\appdata\local\programs\python\python37\lib\site-packages\impacket\dcerpc\v5\transport.py", line 141
    raise RuntimeError, 'virtual function'
                      ^
SyntaxError: invalid syntax

**Comment by mrchelli** [comment]
thanks for the quick answer, i will try that

**Comment by mrchelli** [comment]
it worked, thanks
