### ISSUE TITLE
Dies with "KeyError: 'distinguishedname'"

### ISSUE THREAD

**Issue by RoganDawes** [fox-it/BloodHound.py#14]
I'm trying to extract info from the domain, but it dies part way through (leaving corrupt users and groups files) with the above error.

```
DEBUG: Querying resolver LDAP for DN CN=Server Application Service Accounts,OU=Admin Roles,OU=Corp Resources,DC=example,DC=com
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/bloodhound/__init__.py", line 258, in main
    num_workers=args.workers)
  File "/usr/local/lib/python2.7/dist-packages/bloodhound/__init__.py", line 70, in run
    membership_enum.enumerate_memberships()
  File "/usr/local/lib/python2.7/dist-packages/bloodhound/enumeration/memberships.py", line 214, in enumerate_memberships
    self.enumerate_groups()
  File "/usr/local/lib/python2.7/dist-packages/bloodhound/enumeration/memberships.py", line 197, in enumerate_groups
    resolved_member = self.get_membership(member)
  File "/usr/local/lib/python2.7/dist-packages/bloodhound/enumeration/memberships.py", line 63, in get_membership
    resolved_entry = ADUtils.resolve_ad_entry(qobject)
  File "/usr/local/lib/python2.7/dist-packages/bloodhound/ad/utils.py", line 180, in resolve_ad_entry
    if entry['attributes']['distinguishedName']:
  File "/usr/local/lib/python2.7/dist-packages/ldap3/utils/ciDict.py", line 68, in __getitem__
    return self._store[self._case_insensitive_keymap[self._ci_key(key)]]
KeyError: 'distinguishedname'
```

Any suggestions?

**Comment by RoganDawes** [comment]
```root@kali:~# pip show bloodhound
Name: bloodhound
Version: 0.5.2
Summary: Python based ingestor for BloodHound
Home-page: https://github.com/fox-it/bloodhound.py
Author: Dirk-jan Mollema
Author-email: dirkjan.mollema@fox-it.com
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: pyasn1, dnspython, ldap3, impacket
```

**Comment by mwgielen** [comment]
Can you test it again with the dev branch (commit 84f301870dbca88c4180fc398f4761316e7c672e)?

**Comment by RoganDawes** [comment]
That's worse, unfortunately. It dies almost immediately with:
```
DEBUG: Querying resolver LDAP for SID S-1-5-21-xxxxxxxxx-xxxxxxxxxx-xxxxxxxxxx-xxxxxx
Traceback (most recent call last):
  File "./bloodhound.py", line 5, in <module>
    bloodhound.main()
  File "/root/BloodHound.py/bloodhound/__init__.py", line 259, in main
    num_workers=args.workers)
  File "/root/BloodHound.py/bloodhound/__init__.py", line 70, in run
    membership_enum.enumerate_memberships()
  File "/root/BloodHound.py/bloodhound/enumeration/memberships.py", line 255, in enumerate_memberships
    self.enumerate_users()
  File "/root/BloodHound.py/bloodhound/enumeration/memberships.py", line 166, in enumerate_users
    MembershipEnumerator.add_user_properties(user, entry)
  File "/root/BloodHound.py/bloodhound/enumeration/memberships.py", line 111, in add_user_properties
    props['enabled'] = entry['attributes']['userAccountControl'] & 2 == 0
TypeError: unsupported operand type(s) for &: 'list' and 'int'
```
The previous version was able to extract several tens of thousand users and groups.

This version died after extracting 4064 users, and got no groups.

As an aside, the debug output seems to have changed from master to dev, there was a lot less debug output in dev, hence my statement that it "died almost immediately".

**Comment by dirkjanm** [comment]
This seems to be a different bug related to properties collection (which is not yet in the version you had previously via pip). Could you try to run it without the objectprops collection method to see if the previous bug still occurs?

**Comment by RoganDawes** [comment]
It's still running, but there seems to be a different bug in the latest version.

```
root@kali:~/BloodHound.py# grep Name users.json | uniq -c
  40429  "Name": "@", 
root@kali:~/BloodHound.py# 
```

And:

```
root@kali:~/BloodHound.py# head groups.json 
{"groups":[{
 "Name": "@", 
 "Members": [
  {
   "MemberName": "@", 
   "MemberType": "Unknown"
  }
 ], 
 "Properties": {
  "domain": "za.example.com", 
root@kali:~/BloodHound.py# 
```

**Comment by dirkjanm** [comment]
I've commited another potential fix, could you check if it works with this (I still need to address the ObjectProps collection one)

**Comment by RoganDawes** [comment]
Yup! That completed, thanks!

Out of curiousity, is there a reason that you don't record the DN of each account? I know it is already available, since you output a log message:
```
DEBUG: Querying GC for DN CN=...
```

**Comment by dirkjanm** [comment]
Only the information used by BloodHound is exported, and I don't think it does anything with the DN right now, which is why it isn't exported. The DN is used internally though for resolving and caching.

**Comment by RoganDawes** [comment]
Seems like it would not be any trouble to add it as a node in the json, even if it is ignored by bloodhound. It can be useful if you know the name of your target, but not their account name, for example.

Thanks for your help with this. Much appreciated!
