### ISSUE TITLE
Python Error - "cannot import name cstruct"

### ISSUE THREAD

**Issue by weuroi578** [fox-it/BloodHound.py#19]
When I first attempted to run it the error was related to dissect. I installed it using pip install dissect.

Now I am receiving the error "ImportError: cannot import name cstruct" Below is the error output

Traceback (most recent call last):
  File "./bloodhound.py", line 3, in <module>
    import bloodhound
  File "/opt/BloodHound.py/bloodhound/__init__.py", line 28, in <module>
    from bloodhound.enumeration.computers import ComputerEnumerator
  File "/opt/BloodHound.py/bloodhound/enumeration/computers.py", line 30, in <module>
    from bloodhound.enumeration.memberships import MembershipEnumerator
  File "/opt/BloodHound.py/bloodhound/enumeration/memberships.py", line 33, in <module>
    from bloodhound.enumeration.acls import AclEnumerator, parse_binary_acl
  File "/opt/BloodHound.py/bloodhound/enumeration/acls.py", line 31, in <module>
    from dissect import cstruct
ImportError: cannot import name cstruct

Please help :(

**Comment by rkovaci** [comment]
awesome! I've just re-tested this and it works flawlessly now! thank you for a very quick reply and fix, much appreciated! :)
