### ISSUE TITLE
Syntax Error after installing with pip

### ISSUE THREAD

**Issue by benichmt1** [fox-it/BloodHound.py#23]
Steps to reproduce:
Ubuntu 16.04

Python 2.7.15
pip installed, ldap3,dnspython,impacket all installed via pip

`pip install bloodhound`

Executing gives the following stacktrace:

```bloodhound-python 
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 11, in <module>
    load_entry_point('bloodhound==0.5.1', 'console_scripts', 'bloodhound-python')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/bloodhound/__init__.py", line 26, in <module>
  File "build/bdist.linux-x86_64/egg/bloodhound/ad/domain.py", line 28, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 35, in <module>
    import dns.message
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 191
    print('id %d' % self.id, file=s)
                                 ^
SyntaxError: invalid syntax
```

**Comment by dirkjanm** [comment]
Sounds like something is wrong with your dnspython install. I can't find that line in their source code on GitHub either, try updating/reinstalling it.

**Comment by benichmt1** [comment]
Is there a recommended version of dnspython? I was using 1.16.0

**Comment by benichmt1** [comment]
I was able to fix the issue -

Installed dnspython 2.0.0 from source
installed impacket from source
installed ldap3 from source 

`python3 setup.py install`

python2 was still acting weird :P
