### ISSUE TITLE
bloodhound py puts "." and ".localdomain" at the end of domain controller ip instead of using the domain name i specified

### ISSUE THREAD

**Issue by ghost** [fox-it/BloodHound.py#28]
./bloodhound.py -c all -d htb.local -dc 10.10.10.161 -u #### -p #####
WARNING: Could not find a global catalog server. Please specify one with -gc
INFO: Connecting to LDAP server: 10.10.10.161
Traceback (most recent call last):
  File "./bloodhound.py", line 5, in <module>
    bloodhound.main()
  File "/root/htb/forest/BloodHound.py/bloodhound/__init__.py", line 265, in main
    disable_pooling=args.disable_pooling)
  File "/root/htb/forest/BloodHound.py/bloodhound/__init__.py", line 68, in run
    self.pdc.prefetch_info('objectprops' in collect, 'acl' in collect)
  File "/root/htb/forest/BloodHound.py/bloodhound/ad/domain.py", line 329, in prefetch_info
    self.get_domains(acl=acls)
  File "/root/htb/forest/BloodHound.py/bloodhound/ad/domain.py", line 203, in get_domains
    for entry in entries:
  File "/root/htb/forest/BloodHound.py/bloodhound/ad/domain.py", line 105, in search
    self.ldap_connect()
  File "/root/htb/forest/BloodHound.py/bloodhound/ad/domain.py", line 60, in ldap_connect
    q = self.ad.dnsresolver.query(self.hostname, tcp=self.ad.dns_tcp)
  File "/usr/lib/python2.7/dist-packages/dns/resolver.py", line 1002, in query
    raise NXDOMAIN(qnames=qnames_to_try, responses=nxdomain_responses)
dns.resolver.NXDOMAIN: None of DNS query names exist: 10.10.10.161., 10.10.10.161.localdomain.

if i put a / at the end of the domain name it does consider but then it just times out after 3 seconds. all the prerequisites are fully updated and this persists on both python 2 and 3

**Comment by dirkjanm** [comment]
hey, the DC argument needs a hostname, not an IP. If this hostname does not resolve with your current DNS then you need to specify the DNS server as well (the DNS server should be an IP)
