### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SimplePagedResultsControl'

### ISSUE THREAD

**Issue by ad0nis** [fox-it/BloodHound.py#3]
`# bloodhound-python -u USERNAME -p PASSWORD
INFO: Found AD domain: domain.local
INFO: Connecting to LDAP server: domain.local
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 11, in <module>
    load_entry_point('bloodhound==0.1.0', 'console_scripts', 'bloodhound-python')()
  File "build/bdist.linux-x86_64/egg/bloodhound/__init__.py", line 176, in main
  File "build/bdist.linux-x86_64/egg/bloodhound/__init__.py", line 62, in run
  File "build/bdist.linux-x86_64/egg/bloodhound/ad.py", line 978, in fetch_all
  File "build/bdist.linux-x86_64/egg/bloodhound/ad.py", line 918, in get_rootobject
  File "build/bdist.linux-x86_64/egg/bloodhound/ad.py", line 767, in search
AttributeError: 'module' object has no attribute 'SimplePagedResultsControl'
`

**Comment by dirkjanm** [comment]
Can you make sure you have the latest version of https://github.com/CoreSecurity/impacket installed from Git? This may be causing this error.

**Comment by ad0nis** [comment]
Was on the version in the kali repos. Updated from git last night. Now on version: 0.9.17.dev0. Still having the same problem, even after re-running the setup.py install.

# python bloodhound.py -u USERNAME -p PASSWORD -d domain.local -ns 10.1.2.3
INFO: Found AD domain: sub.domain.local
INFO: Connecting to LDAP server: dns1.sub.domain.local
Traceback (most recent call last):
  File "bloodhound.py", line 5, in <module>
    bloodhound.main()
  File "/path/to/BloodHound.py1/bloodhound/__init__.py", line 176, in main
    bloodhound.run(skip_groups=args.skip_groups, skip_computers=args.skip_computers)
  File "/path/to/BloodHound.py1/bloodhound/__init__.py", line 62, in run
    self.dc.fetch_all()
  File "/path/to/BloodHound.py1/bloodhound/ad.py", line 978, in fetch_all
    self.get_rootobject()
  File "/path/to/BloodHound.py1/bloodhound/ad.py", line 918, in get_rootobject
    entries = self.search(searchBase='', attributes=[], scope=ldapasn1.Scope('baseObject'))
  File "/path/to/BloodHound.py1/bloodhound/ad.py", line 767, in search
    sc = ldap.SimplePagedResultsControl()
AttributeError: 'module' object has no attribute 'SimplePagedResultsControl'

**Comment by dirkjanm** [comment]
Just to be sure, could you show the output of which version is actually imported by Python?
```
user@localhost:~$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from impacket import version
>>> version.BANNER
'Impacket v0.9.17-dev - Copyright 2002-2018 Core Security Technologies\n'
```

**Comment by dirkjanm** [comment]
Since we're now using ldap3 this error should be resolved regardless of the cause.
