### ISSUE TITLE
TypeError: cannot convert 'NoneType' object to bytes

### ISSUE THREAD

**Issue by aaronesau-summit** [fox-it/BloodHound.py#30]
I'm trying to test out the script, but I get a stack trace and am at a bit of a dead end. Am I missing something here or is this just a bug?
```
./bloodhound.py -u username -dc HOSTNAME -ns 127.0.0.1
Password: 
WARNING: Could not find a global catalog server. Please specify one with -gc
INFO: Connecting to LDAP server: HOSTNAME
Traceback (most recent call last):
  File "./bloodhound.py", line 5, in <module>
    bloodhound.main()
  File "/home/aaron/BloodHound.py/bloodhound/__init__.py", line 275, in main
    disable_pooling=args.disable_pooling)
  File "/home/aaron/BloodHound.py/bloodhound/__init__.py", line 68, in run
    self.pdc.prefetch_info('objectprops' in collect, 'acl' in collect)
  File "/home/aaron/BloodHound.py/bloodhound/ad/domain.py", line 329, in prefetch_info
    self.get_domains(acl=acls)
  File "/home/aaron/BloodHound.py/bloodhound/ad/domain.py", line 203, in get_domains
    for entry in entries:
  File "/home/aaron/BloodHound.py/bloodhound/ad/domain.py", line 133, in search
    for e in sresult:
  File "/home/aaron/.local/lib/python3.7/site-packages/ldap3/extend/standard/PagedSearch.py", line 64, in paged_search_generator
    None if cookie is True else cookie)
  File "/home/aaron/.local/lib/python3.7/site-packages/ldap3/core/connection.py", line 779, in search
    check_names=self.check_names)
  File "/home/aaron/.local/lib/python3.7/site-packages/ldap3/operation/search.py", line 347, in search_operation
    request['baseObject'] = LDAPDN(search_base)
  File "/usr/lib/python3.7/site-packages/pyasn1/type/univ.py", line 829, in __init__
    base.SimpleAsn1Type.__init__(self, value, **kwargs)
  File "/usr/lib/python3.7/site-packages/pyasn1/type/base.py", line 267, in __init__
    value = self.prettyIn(value)
  File "/usr/lib/python3.7/site-packages/pyasn1/type/univ.py", line 904, in prettyIn
    return bytes(value)
TypeError: cannot convert 'NoneType' object to bytes
```

**Comment by aaronesau-summit** [comment]
This error probably could be more descriptive, but I eventually determined that this can be fixed using the `-d <name>` argument

**Comment by dirkjanm** [comment]
This is a strange error, which I agree should be more descriptive. Let's keep this issue open so I can track it.

**Comment by Harendra7-D** [comment]
same error is there any solution

**Comment by dirkjanm** [comment]
this should already be fixed in the latest version. if you are on the most recent version please post your command line and a stack trace

**Comment by Harendra7-D** [comment]
Didn't get u what ... Please explain I am a beginner

**Comment by Maninng** [comment]
I had the same Error and just fixed it. It was just a little typographical error in my code, after i found it everything worked fine again.
