### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by gigawalt** [fox-it/BloodHound.py#36]
I installed bloodhound-python, using (the now obsolete) Python 2.7. It seems to work fast and with a nice low memory footprint, but during the group retrieval it crashes (possibly confidential information redacted):

$ uname -a
FreeBSD xxxxxxxx 12.1-RELEASE-p1 FreeBSD 12.1-RELEASE-p1 r356271 GENERIC  amd64
$ bloodhound-python -u xxxxxxxx -p xxxxxxxx -d xxxxxxxx -gc gc._msdcs.xxxxxxxx
INFO: Found AD domain: xxxxxxxx
INFO: Connecting to LDAP server: xxxxxxxx
INFO: Found 1 domains
INFO: Found 2 domains in the forest
INFO: Found 100000 computers
INFO: Found 100000 users
INFO: Connecting to LDAP server: xxxxxxxx
INFO: Connecting to GC LDAP server: gc._msdcs.xxxxxxxx
INFO: Found 100000 groups
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/bloodhound/__init__.py", line 286, in main
    disable_pooling=args.disable_pooling)
  File "/usr/local/lib/python2.7/site-packages/bloodhound/__init__.py", line 85, in run
    trusts_enum.dump_domain(collect)
  File "/usr/local/lib/python2.7/site-packages/bloodhound/enumeration/domains.py", line 119, in dump_domain
    _, aces = parse_binary_acl(domain, 'domain', ADUtils.get_entry_property(domain_object, 'nTSecurityDescriptor'), self
.addc.objecttype_guid_map)
**AttributeError: 'ADDC' object has no attribute 'objecttype_guid_map'**

leaving me with a users.json and groups.json, but an empty domains.json. Is this a know problem? Or maybe the domain I used it on has something unusual in it?

**Comment by nielznl** [comment]
I think the issue is resolved but the repositories have not been updated. If you install the script by cloning the repository `git clone https://github.com/fox-it/BloodHound.py.git` and installing the tool with `cd BloodHound.py && python setup.py install` it should work.

**Comment by gigawalt** [comment]
That's a quick reaction! :-)

I should have mentioned I used a repository install as you guessed. I've built the latest version from source. It then gave me a different error:

[..]
INFO: Found 100000 groups
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 11, in <module>
    load_entry_point('bloodhound==1.0.0', 'console_scripts', 'bloodhound-python')()
  File "build/bdist.freebsd-12.1-RELEASE-p1-amd64/egg/bloodhound/__init__.py", line 286, in main
  File "build/bdist.freebsd-12.1-RELEASE-p1-amd64/egg/bloodhound/__init__.py", line 85, in run
  File "build/bdist.freebsd-12.1-RELEASE-p1-amd64/egg/bloodhound/enumeration/domains.py", line 126, in dump_domain
  File "build/bdist.freebsd-12.1-RELEASE-p1-amd64/egg/bloodhound/ad/trusts.py", line 73, in __init__
  File "/usr/local/lib/python2.7/site-packages/impacket/structure.py", line 84, in __init__
    self.fromString(data)
  File "/usr/local/lib/python2.7/site-packages/impacket/structure.py", line 149, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "/usr/local/lib/python2.7/site-packages/impacket/structure.py", line 380, in unpack
    return unpack(format, data)[0]
struct.error: ('**unpack requires a string argument of length 1**', "When unpacking field 'Revision | <B | [][:1]'")

I then switched to Python 3.7.6 and installed the latest impacket from github. Also again ldns3 version 2.5.1. A similar error occures:

Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 11, in <module>
    load_entry_point('bloodhound==1.0.0', 'console_scripts', 'bloodhound-python')()
  File "/usr/local/lib/python3.7/site-packages/bloodhound-1.0.0-py3.7.egg/bloodhound/__init__.py", line 286, in main
  File "/usr/local/lib/python3.7/site-packages/bloodhound-1.0.0-py3.7.egg/bloodhound/__init__.py", line 85, in run
  File "/usr/local/lib/python3.7/site-packages/bloodhound-1.0.0-py3.7.egg/bloodhound/enumeration/domains.py", line 126,
in dump_domain
  File "/usr/local/lib/python3.7/site-packages/bloodhound-1.0.0-py3.7.egg/bloodhound/ad/trusts.py", line 73, in __init__
  File "/usr/local/lib/python3.7/site-packages/impacket-0.9.21.dev1+20200214.111603.5259ed0f-py3.7.egg/impacket/structure.py", line 84, in __init__
    self.fromString(data)
  File "/usr/local/lib/python3.7/site-packages/impacket-0.9.21.dev1+20200214.111603.5259ed0f-py3.7.egg/impacket/structure.py", line 149, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "/usr/local/lib/python3.7/site-packages/impacket-0.9.21.dev1+20200214.111603.5259ed0f-py3.7.egg/impacket/structure.py", line 382, in unpack
    return unpack(format, data)[0]
TypeError: ("**a bytes-like object is required, not 'list'"**, "When unpacking field 'Revision | <B | [][:1]'")

When I add --collectionmethod Trusts, the error occurs at the start of the data collection. 

I guess this is an impacket issue. Unfortunately, I am not a programmer. I have hacked impacket/structure.py to show some debugging info. It seems it breaks when data equals an empty list. I hacked it to rewrite data if it is an empty list but then it fails a bit later. But I guess this is an issue then for impacket, not for BloodHound.py.

**Comment by tmsteen** [comment]
Used the pip version this morning and got the same initial error. Cloning from the repo worked for me.

**Comment by dirkjanm** [comment]
@gigawalt that seems like a different issue. I'm wondering if you somehow have a trust with a domain without an SID. I just pushed a potential fix for this, could you try updating from the latest commit on master?

**Comment by gigawalt** [comment]
Did so, which yielded this error:
AttributeError: 'ADDomainTrust' object has no attribute 'domainsid'

**Comment by dirkjanm** [comment]
Whoops, that was a typo there, though it confirms my suspicion. I fixed the typo, if you could pull again and test, would be much appreciated.

**Comment by gigawalt** [comment]
\o/ works!

Thanks again for the help (and for making this tool available!)
