### ISSUE TITLE
Cross forest authentication support.

### ISSUE THREAD

**Issue by s3c** [fox-it/BloodHound.py#40]
When attempting to authenticate across forest trusts, I'm getting the following output:

```
INFO: Found AD domain: acme.com
INFO: Connecting to LDAP server: acme.com
Traceback (most recent call last):
  File "./bloodhound.py", line 5, in <module>
    bloodhound.main()
  File "/root/james/BloodHound.py/bloodhound/__init__.py", line 286, in main
    disable_pooling=args.disable_pooling)
  File "/root/james/BloodHound.py/bloodhound/__init__.py", line 72, in run
    self.pdc.prefetch_info('objectprops' in collect, 'acl' in collect)
  File "/root/james/BloodHound.py/bloodhound/ad/domain.py", line 387, in prefetch_info
    self.get_objecttype()
  File "/root/james/BloodHound.py/bloodhound/ad/domain.py", line 216, in get_objecttype
    self.ldap_connect()
  File "/root/james/BloodHound.py/bloodhound/ad/domain.py", line 69, in ldap_connect
    baseDN=self.ad.baseDN, protocol=protocol)
  File "/root/james/BloodHound.py/bloodhound/ad/authentication.py", line 78, in getLDAPConnection
    if not conn.bind():
  File "/usr/lib/python2.7/dist-packages/ldap3/core/connection.py", line 570, in bind
    raise LDAPUnknownAuthenticationMethodError(self.last_error)
ldap3.core.exceptions.LDAPUnknownAuthenticationMethodError: NTLM needs domain\username and a password
```

I did note a previous issue where it's stated that this is not fully implemented:

[https://github.com/fox-it/BloodHound.py/issues/8](https://github.com/fox-it/BloodHound.py/issues/8)

Is this still the case, or is there a way to get this working?

**Comment by dirkjanm** [comment]
How are you providing the autoentication? For cross forest users you should specify `-u user@otherforest.com`

**Comment by s3c** [comment]
Yup format was indeed the problem. New problem, loads of SID resolution errors, and eventually hangs and just sits there with only users.json created. Any ideas?

**Comment by dirkjanm** [comment]
Can you run it with `-w 1 --disable-pooling -v` and let me know where it's stuck (or a stacktrace if there is one)? And also which collection options you are using?

**Comment by dirkjanm** [comment]
Also I just pushed a test to master which uses a timeout for receiving data, could you try with that one?

**Comment by s3c** [comment]
Did and I'm not getting the above error anymore, getting this one now:

```
WARNING: Failed to resolve SAM name REMOTE_FOREST_HOST$ in current forest
WARNING: LDAP Server reported that the search in  for (sAMAccountName=REMOTE_FOREST_USER) does not exist.
```

Keep coming up with new ones, so thanks a bunch.

**Comment by s3c** [comment]
So far my tests have been incomplete, let's try this again, ignoring my previous posts:

```
./bloodhound.py --collectionmethod All,LoggedOn --username SOURCE_USER@SOURCE_FOREST --domain DEST_DOMAIN.DEST_FOREST --workers 16 --global-catalog DC1.DEST_DOMAIN.DEST_FOREST -w 1 --disable-pooling -v
Password: 
DEBUG: Resolved collection methods: localadmin, rdp, psremote, dcom, acl, objectprops, session, loggedon, group, trusts
DEBUG: Using DNS to retrieve domain information
DEBUG: Querying domain controller information from DNS
DEBUG: Using domain hint: DEST_DOMAIN.DEST_FOREST
INFO: Found AD domain: DEST_DOMAIN.DEST_FOREST
DEBUG: Found primary DC: DC1.DEST_DOMAIN.DEST_FOREST
DEBUG: Using LDAP server: DC1.DEST_DOMAIN.DEST_FOREST
DEBUG: Using base DN: DC=DEST_DOMAIN,DC=DEST_FOREST
INFO: Connecting to LDAP server: DC1.DEST_DOMAIN.DEST_FOREST
DEBUG: Authenticating to LDAP server
DEBUG: No LAPS attributes found in schema
INFO: Found 1 domains
INFO: Found 2 domains in the forest
INFO: Found 6347 computers
DEBUG: Writing users to file: users.json
DEBUG: Don't care about acetype 6
INFO: Connecting to LDAP server: DC1.DEST_DOMAIN.DEST_FOREST
DEBUG: Authenticating to LDAP server
DEBUG: Querying resolver LDAP for SID SID_DEST_DOMAIN-512
DEBUG: Querying resolver LDAP for SID SID_DEST_DOMAIN-20053
DEBUG: Querying resolver LDAP for SID SID_DEST_DOMAIN-56673
DEBUG: Querying resolver LDAP for SID SID_DEST_DOMAIN-120436
INFO: Connecting to GC LDAP server: DC1.DEST_DOMAIN.DEST_FOREST
DEBUG: Authenticating to LDAP server
DEBUG: Querying GC for SID SID_SOURCE_DOMAIN-13122
DEBUG: Querying resolver LDAP for SID SID_DEST_DOMAIN-1118
DEBUG: Querying resolver LDAP for SID SID_DEST_DOMAIN-120140
DEBUG: Querying GC for SID SID_SOURCE_DOMAIN-519
DEBUG: Don't care about acetype 6
DEBUG: Querying GC for SID SID_UNKNOWN-1515
WARNING: Could not resolve SID: SID_UNKNOWN-1515
DEBUG: Querying resolver LDAP for SID SID_DEST_DOMAIN-5937
DEBUG: Don't care about acetype 6
DEBUG: Querying resolver LDAP for SID SID_DEST_DOMAIN-39030
WARNING: Could not resolve SID: SID_DEST_DOMAIN-39030
DEBUG: Querying resolver LDAP for SID SID_DEST_DOMAIN-24810
DEBUG: Don't care about acetype 6
DEBUG: Don't care about acetype 6
DEBUG: Don't care about acetype 6
DEBUG: Querying GC for SID SID_UNKNOWN-1380
WARNING: Could not resolve SID: SID_UNKNOWN-1380
DEBUG: Don't care about acetype 6
DEBUG: Don't care about acetype 6
DEBUG: Don't care about acetype 6
DEBUG: Querying resolver LDAP for SID SID_DEST_DOMAIN-29186
DEBUG: Don't care about acetype 6
DEBUG: Don't care about acetype 6
DEBUG: Don't care about acetype 6
DEBUG: Don't care about acetype 6
DEBUG: Don't care about acetype 6
DEBUG: Don't care about acetype 6
...
```

When trying to look up SID_UNKNOWN, wmic hangs, and Get-ADUser gives me a SID not found error.

**Comment by dirkjanm** [comment]
More bugfixes where just pushed to master, maybe those solve your timeout issue as well. Could you check?

**Comment by dirkjanm** [comment]
Closing due to lack of updates, if there is any new info on this feel free to reopen.
