### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'sid'

### ISSUE THREAD

**Issue by vincentcox** [fox-it/BloodHound.py#42]
When running bloodhound.py I got the following error:

```INFO: Connecting to LDAP server: XXXXXXX
INFO: Found 0 domains
INFO: Found 1 domains in the forest
INFO: Found 0 computers
INFO: Found 0 users
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 10, in <module>
    sys.exit(main())
  File "/home/pwnie/.local/lib/python2.7/site-packages/bloodhound/__init__.py", line 286, in main
    disable_pooling=args.disable_pooling)
  File "/home/pwnie/.local/lib/python2.7/site-packages/bloodhound/__init__.py", line 75, in run
    membership_enum.enumerate_memberships()
  File "/home/pwnie/.local/lib/python2.7/site-packages/bloodhound/enumeration/memberships.py", line 488, in enumerate_memberships
    self.enumerate_groups()
  File "/home/pwnie/.local/lib/python2.7/site-packages/bloodhound/enumeration/memberships.py", line 311, in enumerate_groups
    self.write_default_groups()
  File "/home/pwnie/.local/lib/python2.7/site-packages/bloodhound/enumeration/memberships.py", line 437, in write_default_groups
    domainsid = self.addomain.domain_object.sid
AttributeError: 'NoneType' object has no attribute 'sid'
```

I verified with crackmapexe that the credentials were valid and they are working.

Got this issue with cloning from github and via pip install. Any idea why this is happening?

**Comment by dirkjanm** [comment]
Any chance you are specifying the wrong domain and providing a DC manually? It says here it can't find any domains: `INFO: Found 0 domains`. That is not supposed to happen for sure and is likely why it breaks further on.

**Comment by vincentcox** [comment]
Yes, exactly what you described. It was the first time I used this tool, so I had no reference point to compare output to. Thanks for the help and take care in these difficult times.
