### ISSUE TITLE
Python Ingestor errors

### ISSUE THREAD

**Issue by sxplitfirex** [fox-it/BloodHound.py#44]
Hello,
I got the below error when i sused this syntax:
bloodhound-python -u vic -p password1 -ns 192.168.1.10 -d bank.local -dc dc1.bank.local -gc dc1.bank.local

```
INFO: Found AD domain: bank.local
INFO: Connecting to LDAP server: dc1.bank.local
INFO: Found 1 domains
INFO: Found 1 domains in the forest
INFO: Found 107 computers
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 11, in <module>
    load_entry_point('bloodhound==1.0.2', 'console_scripts', 'bloodhound-python')()
  File "build/bdist.linux-x86_64/egg/bloodhound/__init__.py", line 286, in main
  File "build/bdist.linux-x86_64/egg/bloodhound/__init__.py", line 75, in run
  File "build/bdist.linux-x86_64/egg/bloodhound/enumeration/memberships.py", line 487, in enumerate_memberships
  File "build/bdist.linux-x86_64/egg/bloodhound/enumeration/memberships.py", line 144, in enumerate_users
  File "build/bdist.linux-x86_64/egg/bloodhound/ad/domain.py", line 313, in get_users
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by dirkjanm** [comment]
Hi,

The latest version is 1.0.4, please upgrade from pypi or from git and make sure you use the latest version. If the problem still occurs then please post an updated stacktrace.

Thx!

**Comment by sxplitfirex** [comment]
Thanks! That solved the problem.
