### ISSUE TITLE
Key Error in get_membership (v0.7.0)

### ISSUE THREAD

**Issue by AdrianVollmer** [fox-it/BloodHound.py#45]
I got this error (some infos redacted):
```
INFO: Found 64291 users
WARNING: Could not resolve SID: S-1-5-21-XXXXXXXXXXXXXXXXX-44658
...
Traceback (most recent call last):
  File "/home/avollmer/.local/lib/python3.7/site-packages/bloodhound/enumeration/memberships.py", line 57, in get_membership
    resolved_entry = self.addomain.users[member]
KeyError: 'CN=RTCComponentUniversalServices,CN=Users,DC=root,DC=XXXXXX,DC=de'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/avollmer/.local/lib/python3.7/site-packages/bloodhound/enumeration/memberships.py", line 61, in get_membership
    resolved_entry = self.addomain.groups[member]
KeyError: 'CN=RTCComponentUniversalServices,CN=Users,DC=root,DC=XXXXX,DC=de'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/avollmer/.local/lib/python3.7/site-packages/bloodhound/enumeration/memberships.py", line 65, in get_membership
    entry = self.addomain.computers[member]
KeyError: 'CN=RTCComponentUniversalServices,CN=Users,DC=root,DC=XXXXX,DC=de'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ldap3/strategy/base.py", line 823, in sending
    self.connection.socket.sendall(encoded_message)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/avollmer/.local/bin/bloodhound-python", line 10, in <module>
    sys.exit(main())
  File "/home/avollmer/.local/lib/python3.7/site-packages/bloodhound/__init__.py", line 265, in main
    disable_pooling=args.disable_pooling)
  File "/home/avollmer/.local/lib/python3.7/site-packages/bloodhound/__init__.py", line 71, in run
    membership_enum.enumerate_memberships()
  File "/home/avollmer/.local/lib/python3.7/site-packages/bloodhound/enumeration/memberships.py", line 294, in enumerate_memberships
    self.enumerate_groups()
  File "/home/avollmer/.local/lib/python3.7/site-packages/bloodhound/enumeration/memberships.py", line 255, in enumerate_groups
    resolved_member = self.get_membership(member)
  File "/home/avollmer/.local/lib/python3.7/site-packages/bloodhound/enumeration/memberships.py", line 70, in get_membership
    qobject = self.addomain.objectresolver.resolve_distinguishedname(member, use_gc=use_gc)
  File "/home/avollmer/.local/lib/python3.7/site-packages/bloodhound/enumeration/objectresolver.py", line 58, in resolve_distinguishedname
    distinguishedname = self.addc.ldap_get_single(distinguishedname, use_gc=use_gc, use_resolver=True)
  File "/home/avollmer/.local/lib/python3.7/site-packages/bloodhound/ad/domain.py", line 163, in ldap_get_single
    generator=False)
  File "/usr/lib/python3/dist-packages/ldap3/extend/__init__.py", line 125, in paged_search
    paged_criticality)
  File "/usr/lib/python3/dist-packages/ldap3/extend/standard/PagedSearch.py", line 121, in paged_search_accumulator
    paged_criticality):
  File "/usr/lib/python3/dist-packages/ldap3/extend/standard/PagedSearch.py", line 64, in paged_search_generator
    None if cookie is True else cookie)
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 782, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/usr/lib/python3/dist-packages/ldap3/strategy/base.py", line 299, in send
    self.sending(ldap_message)
  File "/usr/lib/python3/dist-packages/ldap3/strategy/base.py", line 834, in sending
    raise communication_exception_factory(LDAPSocketSendError, type(e)(str(e)))(self.connection.last_error)
ldap3.core.exceptions.LDAPSocketSendError: socket sending error[Errno 104] Connection reset by peer
```

This appears to have fixed it, but I'm not sure if this is a proper solution:

```
--- /home/avollmer/.local/lib/python3.7/site-packages/bloodhound/enumeration/memberships.py	2020-04-06 16:36:59.196000000 +0200
+++ memberships.py	2020-04-06 17:25:08.540000000 +0200
@@ -252,10 +252,7 @@
                 group['Properties']['description'] = ADUtils.get_entry_property(entry, 'description')
 
             for member in entry['attributes']['member']:
-                try:
-                    resolved_member = self.get_membership(member)
-                except KeyError:
-                    resolved_member = None
+                resolved_member = self.get_membership(member)
                 if resolved_member:
                     group['Members'].append(resolved_member)
```

**Comment by dirkjanm** [comment]
The KeyError is intentional, however the underlying problem is that the connection with the LDAP server was reset during operation. This is not intentional and some better error handling is needed here. The positive thing is that there's a good chance collection will run fine if you try it again.

**Comment by AdrianVollmer** [comment]
Ah, so the patch didn't really do anything and I just got lucky when I ran it a second time.

**Comment by dirkjanm** [comment]
I'll put this on the backlog but close this one as it's not really descriptive of the actual problem.
