### ISSUE TITLE
Kali 2020 issue

### ISSUE THREAD

**Issue by Chantal2019** [fox-it/BloodHound.py#50]
Hi :)

I made sure all my pacakges are up to date but i keep getting this error :(

```
Traceback (most recent call last):
  File "bloodhound.py", line 5, in <module>
    bloodhound.main()
  File "/root/HTB/blackfield/BloodHound.py/bloodhound/__init__.py", line 284, in main
    bloodhound.run(collect=collect,
  File "/root/HTB/blackfield/BloodHound.py/bloodhound/__init__.py", line 72, in run
    self.pdc.prefetch_info('objectprops' in collect, 'acl' in collect)
  File "/root/HTB/blackfield/BloodHound.py/bloodhound/ad/domain.py", line 394, in prefetch_info
    self.get_objecttype()
  File "/root/HTB/blackfield/BloodHound.py/bloodhound/ad/domain.py", line 224, in get_objecttype
    self.ldap_connect()
  File "/root/HTB/blackfield/BloodHound.py/bloodhound/ad/domain.py", line 68, in ldap_connect
    ldap = self.ad.auth.getLDAPConnection(hostname=ip,
  File "/root/HTB/blackfield/BloodHound.py/bloodhound/ad/authentication.py", line 78, in getLDAPConnection
    if not conn.bind():
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 563, in bind
    response = self.do_ntlm_bind(controls)
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 1302, in do_ntlm_bind
    request = bind_operation(self.version, 'SICILY_RESPONSE_NTLM', ntlm_client, result['server_creds'])
  File "/usr/lib/python3/dist-packages/ldap3/operation/bind.py", line 81, in bind_operation
    server_creds = name.create_authenticate_message()
  File "/usr/lib/python3/dist-packages/ldap3/utils/ntlm.py", line 379, in create_authenticate_message
    nt_challenge_response = self.compute_nt_response()
  File "/usr/lib/python3/dist-packages/ldap3/utils/ntlm.py", line 485, in compute_nt_response
    response_key_nt = self.ntowf_v2()
  File "/usr/lib/python3/dist-packages/ldap3/utils/ntlm.py", line 497, in ntowf_v2
    return hmac.new(password_digest, (self.user_name.upper() + self.user_domain).encode('utf-16-le')).digest()
  File "/usr/lib/python3.8/hmac.py", line 153, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3.8/hmac.py", line 51, in __init__
    raise TypeError("Missing required parameter 'digestmod'.")
TypeError: Missing required parameter 'digestmod'.
```

**Comment by Chantal2019** [comment]
and I get the same for ldapdump as well

**Comment by dirkjanm** [comment]
That is caused by an outdated version of ldap3. Make sure to remove any version preinstalled with Kali and update to the latest (or run bloodhound.py in a virtualenv)

**Comment by Chantal2019** [comment]
thank you so much :)
