### ISSUE TITLE
connects but throws an error NoneType object has no attribute 'sid'

### ISSUE THREAD

**Issue by rocketscientist911** [fox-it/BloodHound.py#52]
I have tried specifying multiple user accounts but its still the same. Anyways I am passing with --hashes option! i have tried specifinyg password also and its same.

```
INFO: Found 0 domains
INFO: Found 1 domains in the forest
INFO: Found 0 computers
INFO: Found 0 users
Traceback (most recent call last):
  File "bloodhound.py", line 5, in <module>
    bloodhound.main()
  File "/home/xx/BloodHound.py/bloodhound/__init__.py", line 286, in main
    disable_pooling=args.disable_pooling)
  File "/home/xx/BloodHound.py/bloodhound/__init__.py", line 75, in run
    membership_enum.enumerate_memberships()
  File "/home/xx/BloodHound.py/bloodhound/enumeration/memberships.py", line 489, in enumerate_memberships
    self.enumerate_groups()
  File "/home/xx/BloodHound.py/bloodhound/enumeration/memberships.py", line 312, in enumerate_groups
    self.write_default_groups()
  File "/home/xx/BloodHound.py/bloodhound/enumeration/memberships.py", line 438, in write_default_groups
    domainsid = self.addomain.domain_object.sid
AttributeError: 'NoneType' object has no attribute 'sid'

```

**Comment by rocketscientist911** [comment]
> option!

I have tried with

**Comment by rocketscientist911** [comment]
nevermind i made a typo on domain and had to specify  --disable-pooling -w 1

Would have been nicer if it said haha incorrect domain :P
