### ISSUE TITLE
Bloodhound-python does not work when LDAP signing is required

### ISSUE THREAD

**Issue by sebrink** [fox-it/BloodHound.py#53]
Bloodhound-python does not work when LDAP signing is required. Errors with debug mode can be found below.

I have verified that my installation of BloodHound.py works on a machine where LDAP signing is not enabled.

Let me know if there is anything you'd like me to clarify.

```
# bloodhound-python -u "validUser" --hashes "aad3b435b51404eeaad3b435b51404ee:validHash" -d corp.local -dc dc.corp.local -gc dc.corp.local -v
DEBUG: Authentication: NTLM hashes
DEBUG: Resolved collection methods: localadmin, session, group, trusts
DEBUG: Using DNS to retrieve domain information
DEBUG: Querying domain controller information from DNS
DEBUG: Using domain hint: corp.local
INFO: Found AD domain: corp.local
DEBUG: Found primary DC: dc.corp.local
DEBUG: Using LDAP server: dc.corp.local
DEBUG: Using base DN: DC=dc,DC=corp,DC=local
INFO: Connecting to LDAP server: dc.corp.local
DEBUG: Authenticating to LDAP server
WARNING: LDAP Authentication is refused because LDAP signing is enabled. Trying to connect over LDAPS instead...
DEBUG: Authenticating to LDAP server
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 11, in <module>
    load_entry_point('bloodhound==1.0.4', 'console_scripts', 'bloodhound-python')()
  File "build/bdist.linux-x86_64/egg/bloodhound/__init__.py", line 286, in main
  File "build/bdist.linux-x86_64/egg/bloodhound/__init__.py", line 72, in run
  File "build/bdist.linux-x86_64/egg/bloodhound/ad/domain.py", line 394, in prefetch_info
  File "build/bdist.linux-x86_64/egg/bloodhound/ad/domain.py", line 224, in get_objecttype
  File "build/bdist.linux-x86_64/egg/bloodhound/ad/domain.py", line 69, in ldap_connect
  File "build/bdist.linux-x86_64/egg/bloodhound/ad/authentication.py", line 83, in getLDAPConnection
  File "build/bdist.linux-x86_64/egg/bloodhound/ad/authentication.py", line 78, in getLDAPConnection
  File "/usr/local/lib/python2.7/dist-packages/ldap3/core/connection.py", line 524, in bind
    self.open(read_server_info=False)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/strategy/sync.py", line 56, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/strategy/base.py", line 147, in open
    raise LDAPSocketOpenError('unable to open socket', exception_history)
ldap3.core.exceptions.LDAPSocketOpenError: ('unable to open socket', [(LDAPSocketOpenError('socket ssl wrapping error: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:727)',), ('10.10.10.10', 636))])```

**Comment by dirkjanm** [comment]
While ldap signing triggers this issue, it is not the root cause. Because signing is required, it retries via ldap over TLS, where signing is not required. At that point it fails. This could be an issue with the ciphers supported by your openssl version.

**Comment by sebrink** [comment]
Ah okay, I'll do some testing and get back to you on this, appreciate the fast response!

**Comment by sebrink** [comment]
Tried the docker version and it worked! I'll take a look at my setup and figure out that OpenSSL issue, thanks for the advice!
