### ISSUE TITLE
Crash argument 

### ISSUE THREAD

**Issue by Green-Wolf** [fox-it/BloodHound.py#6]
Hey, great concept for a tool, going to be excellent doing this from kali with an ntlm hash. 

However when i run it, it crashes due to one of the arguments being null? I can't see where the nonetype would be coming from. 

```
# bloodhound-python -u admin -p password -d target.domain.com
INFO: Found AD domain: target.domain.com
INFO: Connecting to LDAP server: xxxxx-targetdc52.target.domain.com
INFO: Found 1 domains
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/bloodhound/__init__.py", line 172, in main
    bloodhound.run(skip_groups=args.skip_groups, skip_computers=args.skip_computers)
  File "/usr/local/lib/python2.7/dist-packages/bloodhound/__init__.py", line 63, in run
    self.dc.fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/bloodhound/ad/domain.py", line 613, in fetch_all
    self.get_computers()
  File "/usr/local/lib/python2.7/dist-packages/bloodhound/ad/domain.py", line 461, in get_computers
    for entry in entries:
  File "/usr/local/lib/python2.7/dist-packages/bloodhound/ad/domain.py", line 368, in search
    for e in result:
  File "/usr/local/lib/python2.7/dist-packages/ldap3/extend/standard/PagedSearch.py", line 63, in paged_search_generator
    None if cookie is True else cookie)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/core/connection.py", line 762, in search
    self.server.schema if self.server else None)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/operation/search.py", line 370, in search_operation
    request['filter'] = compile_filter(parse_filter(search_filter, schema, auto_escape, auto_encode).elements[0])  # parse the searchFilter string and compile it starting from the root node
  File "/usr/local/lib/python2.7/dist-packages/ldap3/operation/search.py", line 230, in compile_filter
    boolean_filter[pos] = compile_filter(element)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/operation/search.py", line 242, in compile_filter
    boolean_filter['innerNotFilter'] = compile_filter(filter_node.elements[0])
  File "/usr/local/lib/python2.7/dist-packages/ldap3/operation/search.py", line 267, in compile_filter
    matching_filter['dnAttributes'] = DnAttributes(filter_node.assertion['dnAttributes'])
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/univ.py", line 103, in __init__
    base.AbstractSimpleAsn1Item.__init__(self, value, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/base.py", line 240, in __init__
    value = self.prettyIn(value)
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/univ.py", line 254, in prettyIn
    return int(value)
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by mwgielen** [comment]
Hi,

I've seen this problem myself as well, can you try running bloodhound.py in a virtualenv / pipenv? To make sure this is not caused by outdated / wrong versions of packages.

**Comment by Green-Wolf** [comment]
Hi, thanks for the help, that pip install upgrade fixed the problem above but instead gave another one:

```
INFO: Found 1 domains
INFO: Found 394 computers
INFO: Found 67 groups
INFO: Found 251 trusts
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/bloodhound/__init__.py", line 172, in main
    bloodhound.run(skip_groups=args.skip_groups, skip_computers=args.skip_computers)
  File "/usr/local/lib/python2.7/dist-packages/bloodhound/__init__.py", line 63, in run
    self.dc.fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/bloodhound/ad/domain.py", line 618, in fetch_all
    self.dump_memberships()
  File "/usr/local/lib/python2.7/dist-packages/bloodhound/ad/domain.py", line 576, in dump_memberships
    self.write_membership(resolved_entry, m, out)
  File "/usr/local/lib/python2.7/dist-packages/bloodhound/ad/domain.py", line 542, in write_membership
    logging.warning('Warning: Unknown group %d' % membership)
TypeError: %d format: a number is required, not unicode
```

**Comment by dirkjanm** [comment]
That does look like a typo. I've committed a small fix to correct this. Could you clone the repository from git, run `pip install . --upgrade` and try again to see if it fixes it? Thanks for testing!

**Comment by Green-Wolf** [comment]
Just ran the upgrade and it ran perfectly. Uploaded the csv's to bloodhound and everything works. Great job 👍Thanks again for the awesome tool!

**Comment by dirkjanm** [comment]
I've made the dependencies more explicit in `v0.3.1`, which should prevent this in the future.

**Comment by robertjriga** [comment]
ERROR: Package 'dnspython' requires a different Python: 2.7.18 not in '>=3.6'
python2 --version
Python 2.7.18
python3 --version
Python 3.8.4rc1

**Comment by dirkjanm** [comment]
@robertjriga install it with pip3 or install dnspython 1.16.0 first manually
