### ISSUE TITLE
KeyError: (0,12) crash

### ISSUE THREAD

**Issue by hubert3** [fox-it/BloodHound.py#7]
Any way I can help to debug this?

$ python bloodhound.py -d mydomain -v -u myuser -p mypass
[...]
INFO: Connecting to LDAP server: mydc.domain.com
DEBUG: Authenticating to LDAP server
INFO: Found 1 domains
Traceback (most recent call last):
  File "bloodhound.py", line 5, in <module>
    bloodhound.main()
  File "/Users/hubert/BloodHound.py/bloodhound/__init__.py", line 182, in main
    bloodhound.run(skip_groups=args.skip_groups, skip_computers=args.skip_computers, skip_trusts=args.skip_trusts, num_workers=args.workers)
  File "/Users/hubert/BloodHound.py/bloodhound/__init__.py", line 63, in run
    self.dc.fetch_all()
  File "/Users/hubert/BloodHound.py/bloodhound/ad/domain.py", line 619, in fetch_all
    self.get_computers()
  File "/Users/hubert/BloodHound.py/bloodhound/ad/domain.py", line 467, in get_computers
    for entry in entries:
  File "/Users/hubert/BloodHound.py/bloodhound/ad/domain.py", line 374, in search
    for e in result:
  File "/usr/local/lib/python2.7/site-packages/ldap3/extend/standard/PagedSearch.py", line 64, in paged_search_generator
    None if cookie is True else cookie)
  File "/usr/local/lib/python2.7/site-packages/ldap3/core/connection.py", line 775, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/usr/local/lib/python2.7/site-packages/ldap3/strategy/sync.py", line 142, in post_send_search
    responses, result = self.get_response(message_id)
  File "/usr/local/lib/python2.7/site-packages/ldap3/strategy/base.py", line 331, in get_response
    responses = self._get_response(message_id)
  File "/usr/local/lib/python2.7/site-packages/ldap3/strategy/sync.py", line 167, in _get_response
    ldap_resp = decode_message_fast(response)
  File "/usr/local/lib/python2.7/site-packages/ldap3/utils/asn1.py", line 104, in decode_message_fast
    decoded = decode_sequence(message, ber_value_offset, ber_len + ber_value_offset, LDAP_MESSAGE_CONTEXT)
  File "/usr/local/lib/python2.7/site-packages/ldap3/utils/asn1.py", line 124, in decode_sequence
    value = ber_decoder(message, start, start + ber_len, context_decoders)  # call value decode function
  File "/usr/local/lib/python2.7/site-packages/ldap3/utils/asn1.py", line 124, in decode_sequence
    value = ber_decoder(message, start, start + ber_len, context_decoders)  # call value decode function
  File "/usr/local/lib/python2.7/site-packages/ldap3/utils/asn1.py", line 124, in decode_sequence
    value = ber_decoder(message, start, start + ber_len, context_decoders)  # call value decode function
  File "/usr/local/lib/python2.7/site-packages/ldap3/utils/asn1.py", line 120, in decode_sequence
    ber_decoder = DECODERS[(ber_class, octet & 0b00011111)] if ber_class < 2 else None
KeyError: (0, 12)

**Comment by dirkjanm** [comment]
Can you verify that you have the latest version of ldap3 and pyasn1? Try upgrading with `pip install ldap3 pyasn1 --upgrade`. Let me know if that fixes it or if you still have problems afterwards.

**Comment by hubert3** [comment]
Upgraded from ldap3-2.4.1 to ldap3-2.5 and I now get a different error, dns.exception.Timeout: The DNS operation timed out after 3 seconds, doesn't help if I change this to 10

Will try to debug some more later

**Comment by dirkjanm** [comment]
It is a bit odd that it was able to establish an LDAP connection before the upgrade but not after, especially if it is DNS related. Are you sure this isn't related to your network connectivity or command line parameters?

**Comment by dirkjanm** [comment]
Closing due to lack of feedback. Feel free to reopen if there is more current information.
