### ISSUE TITLE
LDAPSocketReceiveError (timeout config to 70sec)

### ISSUE THREAD

**Issue by antonbek89** [fox-it/BloodHound.py#74]
Someone facing this issue?

My command was
bloodhound-python -u <user> --hashes <>:<> -c all -d DOMAIN.COM --dns-tcp --dns-timeout 70 -ns DC.DOMAIN.COM -v

(I check the user and NTLM with Impact and its work great)

DEBUG: Authenticating to LDAP server
```
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\bloodhound-python.exe\__main__.py", line 7, in <module>
  File "c:\python27\lib\site-packages\bloodhound\__init__.py", line 300, in main
    timestamp=timestamp)
  File "c:\python27\lib\site-packages\bloodhound\__init__.py", line 73, in run
    self.pdc.prefetch_info('objectprops' in collect, 'acl' in collect)
  File "c:\python27\lib\site-packages\bloodhound\ad\domain.py", line 393, in prefetch_info
    self.get_objecttype()
  File "c:\python27\lib\site-packages\bloodhound\ad\domain.py", line 223, in get_objecttype
    self.ldap_connect()
  File "c:\python27\lib\site-packages\bloodhound\ad\domain.py", line 69, in ldap_connect
    baseDN=self.ad.baseDN, protocol=protocol)
  File "c:\python27\lib\site-packages\bloodhound\ad\authentication.py", line 78, in getLDAPConnection
    if not conn.bind():
  File "c:\python27\lib\site-packages\ldap3\core\connection.py", line 671, in bind
    self.refresh_server_info()
  File "c:\python27\lib\site-packages\ldap3\core\connection.py", line 1427, in refresh_server_info
    self.server.get_info_from_server(self)
  File "c:\python27\lib\site-packages\ldap3\core\server.py", line 525, in get_info_from_server
    self._get_schema_info(connection)
  File "c:\python27\lib\site-packages\ldap3\core\server.py", line 489, in _get_schema_info
    get_operational_attributes=True
  File "c:\python27\lib\site-packages\ldap3\core\connection.py", line 853, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "c:\python27\lib\site-packages\ldap3\strategy\sync.py", line 178, in post_send_search
    responses, result = self.get_response(message_id)
  File "c:\python27\lib\site-packages\ldap3\strategy\base.py", line 355, in get_response
    responses = self._get_response(message_id, timeout)
  File "c:\python27\lib\site-packages\ldap3\strategy\sync.py", line 196, in _get_response
    responses = self.receiving()
  File "c:\python27\lib\site-packages\ldap3\strategy\sync.py", line 99, in receiving
    raise communication_exception_factory(LDAPSocketReceiveError, type(e)(str(e)))(self.connection.last_error)
ldap3.core.exceptions.LDAPSocketReceiveError: error receiving data: timed out
```

**Comment by eversinc33** [comment]
Same. Would appreciate if someone found the cause/solution.
