### ISSUE TITLE
Connect refused

### ISSUE THREAD

**Issue by belveruski** [fox-it/BloodHound.py#87]
Hi, 

I don't understand I have an error when authenticating to the LDAP server even though the credentials are correct.

Command:
```bash
$  bloodhound-python -u admin -p StrongPass123! -d cyberloop.local -vv -ns 192.168.56.10
```
Error:
```text
DEBUG: Authentication: username/password
DEBUG: Resolved collection methods: group, trusts, localadmin, session
DEBUG: Using DNS to retrieve domain information
DEBUG: Querying domain controller information from DNS
DEBUG: Using domain hint: cyberloop.local
INFO: Found AD domain: cyberloop.local
DEBUG: Found primary DC: domain-controller.cyberloop.local
DEBUG: Found Global Catalog server: domain-controller.cyberloop.local
DEBUG: Using LDAP server: domain-controller.cyberloop.local
DEBUG: Using base DN: DC=cyberloop,DC=local
INFO: Connecting to LDAP server: domain-controller.cyberloop.local
DEBUG: Authenticating to LDAP server
Traceback (most recent call last):
  File "/home/vagrant/.local/bin/bloodhound-python", line 8, in <module>
    sys.exit(main())
  File "/home/vagrant/.local/lib/python3.8/site-packages/bloodhound/__init__.py", line 297, in main
    bloodhound.run(collect=collect,
  File "/home/vagrant/.local/lib/python3.8/site-packages/bloodhound/__init__.py", line 73, in run
    self.pdc.prefetch_info('objectprops' in collect, 'acl' in collect)
  File "/home/vagrant/.local/lib/python3.8/site-packages/bloodhound/ad/domain.py", line 403, in prefetch_info
    self.get_objecttype()
  File "/home/vagrant/.local/lib/python3.8/site-packages/bloodhound/ad/domain.py", line 223, in get_objecttype
    self.ldap_connect()
  File "/home/vagrant/.local/lib/python3.8/site-packages/bloodhound/ad/domain.py", line 68, in ldap_connect
    ldap = self.ad.auth.getLDAPConnection(hostname=ip,
  File "/home/vagrant/.local/lib/python3.8/site-packages/bloodhound/ad/authentication.py", line 78, in getLDAPConnection
    if not conn.bind():
  File "/home/vagrant/.local/lib/python3.8/site-packages/ldap3/core/connection.py", line 589, in bind
    self.open(read_server_info=False)
  File "/home/vagrant/.local/lib/python3.8/site-packages/ldap3/strategy/sync.py", line 57, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/home/vagrant/.local/lib/python3.8/site-packages/ldap3/strategy/base.py", line 146, in open
    raise exception_history[0][0]
ldap3.core.exceptions.LDAPSocketOpenError: socket connection error while opening: [Errno 111] Connection refused
```

**Comment by dirkjanm** [comment]
You should test network connectivity to this specific domain controller. This is an error that shows up before authentication so it's not related to the credentials. Try debugging with ncat on the same port (389 for normal ldap 636 for ldaps).
