### ISSUE TITLE
Error "invalid attribute type unixuserpassword"

### ISSUE THREAD

**Issue by corsch** [fox-it/BloodHound.py#88]
When running the new Version 1.2.x version to an old 2003 DC, we get the following error. The old 1.1.1 did work without issues. 

python3 bloodhound.py -u <username> -d <domain> -ns <nameserver> -c DCOnly
Password: <password>

```

INFO: Found AD domain: <domain>
INFO: Connecting to LDAP server: <2003_DC>.<domain>
INFO: Found 1 domains
INFO: Found 1 domains in the forest
INFO: Found 1 computers
Traceback (most recent call last):
  File "<path>/BloodHound.py/bloodhound.py", line 5, in <module>
    bloodhound.main()
  File "<path>/BloodHound.py/bloodhound/__init__.py", line 297, in main
    bloodhound.run(collect=collect,
  File "<path>/BloodHound.py/bloodhound/__init__.py", line 76, in run
    membership_enum.enumerate_memberships(timestamp=timestamp)
  File "<path>/BloodHound.py/bloodhound/enumeration/memberships.py", line 533, in enumerate_memberships
    self.enumerate_users(timestamp)
  File "<path>/BloodHound.py/bloodhound/enumeration/memberships.py", line 169, in enumerate_users
    for entry in entries:
  File "<path>/BloodHound.py/bloodhound/ad/domain.py", line 156, in search
    for e in sresult:
  File "/usr/local/lib/python3.9/dist-packages/ldap3/extend/standard/PagedSearch.py", line 56, in paged_search_generator
    result = connection.search(search_base,
  File "/usr/local/lib/python3.9/dist-packages/ldap3/core/connection.py", line 836, in search
    raise LDAPAttributeError(self.last_error)
ldap3.core.exceptions.LDAPAttributeError: invalid attribute type unixuserpassword

```

**Comment by corsch** [comment]
The error seems to be in the "ObjectProps" query

**Comment by dirkjanm** [comment]
hey, if you leave out that property in the source, does it error out on a different property? I can add a check for the unixuserpassword property but I don't have access to a 2003 DC so I can't test if this is the only property with problems

**Comment by corsch** [comment]
Thank you very much, this is a valid workaround :)
As always, you are a great help!

I will now investigate the attribute on this specific old server.

**Comment by corsch** [comment]
Sorry for the late reply, removing "unixuserpassword property" did solve my issue.
